service: dealerone-rebelpixel-ca

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  stackName: dealerone-rebelpixel-ca
  deploymentBucket:
    name: serverless-gatsby-deployments

resources:
  Resources:
    HostingBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: dealerone.rebelpixel.ca
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html